name: Public app
on:
  push:
    branches:
      - main
permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  Build_application:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout github
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Debug PAT
        run: echo "${{ secrets.PAT_TOKEN }}"